import React, { useState, useEffect } from 'react';
import { Copy, Check, FileText, Download, Sparkles, Send, ShieldCheck } from 'lucide-react';
import { generateWeeklyReportDirect } from '../services/firestoreService';

export const WeeklyReportView: React.FC = () => {
  const [reportText, setReportText] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [copied, setCopied] = useState<boolean>(false);

  const fetchReport = async () => {
    setIsLoading(true);
    try {
      const res = await fetch('/api/reports/weekly');
      if (res.ok) {
        const data = await res.json();
        setReportText(data.reportText);
        setIsLoading(false);
        return;
      }
    } catch (err) {
      console.warn('API report fetch failed, fallback to Firestore:', err);
    }

    try {
      const data = await generateWeeklyReportDirect();
      setReportText(data.reportText);
    } catch (fsErr) {
      console.error('Firestore report generation failed:', fsErr);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchReport();
  }, []);

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  const handleDownloadTxt = () => {
    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `lab_pulse_weekly_executive_report_${new Date().toISOString().split('T')[0]}.txt`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="max-w-4xl mx-auto px-4 py-6 space-y-6">
      {/* Header */}
      <div className="bg-white border-2 border-[#1A1A1A] rounded-md p-6 shadow-[4px_4px_0px_0px_#1A1A1A] flex flex-wrap items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="bg-[#1D4ED8] text-white text-[10px] font-mono font-bold px-2 py-0.5 rounded uppercase">
              EXECUTIVE BRIEFING GENERATOR
            </span>
            <span className="bg-emerald-100 text-emerald-800 text-[10px] font-mono font-bold px-2 py-0.5 rounded border border-emerald-300">
              ZERO-CONFIG READY
            </span>
          </div>
          <h2 className="text-xl font-mono font-extrabold text-[#1A1A1A] uppercase flex items-center gap-2">
            <FileText className="w-6 h-6 text-[#1D4ED8]" />
            WEEKLY PROGRAM SUMMARY REPORT
          </h2>
          <p className="text-xs text-gray-600 font-sans mt-1">
            Pre-formatted plain-text executive summary auto-compiled for email broadcasts, C-suite updates, or Slack reports.
          </p>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={handleDownloadTxt}
            disabled={isLoading}
            className="bg-[#1A1A1A] text-white border-2 border-[#1A1A1A] px-4 py-2.5 rounded font-mono font-extrabold text-xs shadow-[3px_3px_0px_0px_#1A1A1A] hover:bg-gray-800 flex items-center gap-1.5 transition-all"
          >
            <Download className="w-4 h-4 text-amber-300" />
            Download .TXT
          </button>

          <button
            onClick={handleCopy}
            disabled={isLoading}
            className="bg-[#1D4ED8] text-white border-2 border-[#1A1A1A] px-5 py-2.5 rounded font-mono font-extrabold text-xs shadow-[3px_3px_0px_0px_#1A1A1A] hover:bg-blue-800 flex items-center gap-2 transition-all"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-300" /> : <Copy className="w-4 h-4" />}
            {copied ? 'COPIED TO CLIPBOARD!' : 'COPY TO CLIPBOARD'}
          </button>
        </div>
      </div>

      {/* Report Box */}
      <div className="bg-[#1A1A1A] text-emerald-400 border-2 border-[#1A1A1A] rounded-md p-5 sm:p-6 shadow-[6px_6px_0px_0px_#1A1A1A] font-mono text-xs leading-relaxed overflow-x-auto relative">
        <div className="flex items-center justify-between border-b border-gray-700 pb-3 mb-4 text-gray-400 text-[11px]">
          <span className="flex items-center gap-1.5 text-amber-400 font-bold">
            <ShieldCheck className="w-4 h-4" /> COMPLETED FIELD AUDIT SUMMARY
          </span>
          <span>AUTOGENERATED BY LAB PULSE ENGINE</span>
        </div>

        {isLoading ? (
          <div className="py-12 text-center text-gray-400 animate-pulse">
            Generating real-time field report...
          </div>
        ) : (
          <pre className="whitespace-pre-wrap font-mono selection:bg-emerald-800 selection:text-white">
            {reportText}
          </pre>
        )}
      </div>
    </div>
  );
};
